version: '3'
services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data/bitwarden/:/data/
    networks:
      - bitwarden

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - ./data/pihole/etc/:/etc/pihole/
      - ./data/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
    networks:
      - bitwarden

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: bitwarden-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf/:/etc/letsencrypt/
      - ./data/certbot/www/:/var/www/certbot/
      - ./data/nginx/:/etc/nginx/
    networks:
      - bitwarden
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: bitwarden-certbot
    volumes:
      - ./data/certbot/conf/:/etc/letsencrypt/
      - ./data/certbot/www/:/var/www/certbot/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks: 
  bitwarden:
    external: true